#!/bin/bash

echo 'Please enter what you want to do: '
options=("Run record link analysis" "Open Map of ECCSC Responses" "Close program")
select opt in "${options[@]}"
do
    case $opt in
        "Run record link analysis")
            echo "You chose to run record link analysis"
            python3 __main__.py "run"
            echo "You are still in options menu, reminder:"
            echo "1 to run record link analysis"
            echo "2 to open map of ECCSC responses"
            echo "3 to close this program"
            ;;
        "Open Map of ECCSC Responses")
            echo "You chose to open map of ECCSC responses"
            python3 __main__.py "map"
            echo "You are still in options menu, reminder:"
            echo "1 to run record link analysis"
            echo "2 to open map of ECCSC responses"
            echo "3 to close this program"
            ;;
        "Close program")
            echo "Closing program"
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
